/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'app\'">' + entity + '</span>' + html;
	}
	var icons = {
			'tg-user' : '&#x31;',
			'tg-users' : '&#x32;',
			'tg-bubble' : '&#x33;',
			'tg-bubble-2' : '&#x34;',
			'tg-bubbles' : '&#x35;',
			'tg-bubbles-2' : '&#x36;',
			'tg-lock' : '&#x37;',
			'tg-lock-2' : '&#x38;',
			'tg-unlocked' : '&#x39;',
			'tg-key' : '&#x30;',
			'tg-fire' : '&#x71;',
			'tg-dashboard' : '&#x61;',
			'tg-meter' : '&#x62;',
			'tg-pie' : '&#xe00d;',
			'tg-cog' : '&#x77;',
			'tg-cog-2' : '&#x65;',
			'tg-clock' : '&#x72;',
			'tg-home' : '&#x74;',
			'tg-office' : '&#x79;',
			'tg-pencil' : '&#x75;',
			'tg-image' : '&#x69;',
			'tg-image-2' : '&#x6f;',
			'tg-camera' : '&#x70;',
			'tg-folder' : '&#x5b;',
			'tg-folder-open' : '&#x73;',
			'tg-switch' : '&#x64;',
			'tg-list' : '&#x66;',
			'tg-menu' : '&#x67;',
			'tg-menu-2' : '&#x68;',
			'tg-cloud' : '&#x6a;',
			'tg-cloud-upload' : '&#x6b;',
			'tg-remove' : '&#xe01f;',
			'tg-remove-2' : '&#xe020;',
			'tg-briefcase' : '&#xe021;',
			'tg-hammer' : '&#xe022;',
			'tg-upload' : '&#xe023;',
			'tg-link' : '&#xe024;',
			'tg-attachment' : '&#xe025;',
			'tg-eye-blocked' : '&#xe027;',
			'tg-bookmark' : '&#xe026;',
			'tg-bookmarks' : '&#xe028;',
			'tg-heart' : '&#xe029;',
			'tg-heart-broken' : '&#xe02a;',
			'tg-thumbs-up' : '&#xe02b;',
			'tg-thumbs-up-2' : '&#xe02c;',
			'tg-star' : '&#xe02d;',
			'tg-star-2' : '&#xe02e;',
			'tg-star-3' : '&#xe02f;',
			'tg-close' : '&#xe030;',
			'tg-checkmark' : '&#xe031;',
			'tg-checkmark-2' : '&#xe032;',
			'tg-cancel-circle' : '&#xe033;',
			'tg-checkmark-circle' : '&#xe034;',
			'tg-spam' : '&#xe035;',
			'tg-info' : '&#xe036;',
			'tg-info-2' : '&#xe037;',
			'tg-question' : '&#xe038;',
			'tg-blocked' : '&#xe039;',
			'tg-warning' : '&#xe03a;',
			'tg-notification' : '&#xe03b;',
			'tg-play' : '&#xe03c;',
			'tg-pause' : '&#xe03d;',
			'tg-backward' : '&#xe03e;',
			'tg-stop' : '&#xe03f;',
			'tg-volume-medium' : '&#xe040;',
			'tg-checkbox-checked' : '&#xe041;',
			'tg-checkbox-unchecked' : '&#xe042;',
			'tg-checkbox-partial' : '&#xe043;',
			'tg-radio-checked' : '&#xe044;',
			'tg-radio-unchecked' : '&#xe045;',
			'tg-share' : '&#xe046;',
			'tg-youtube' : '&#xe047;',
			'tg-facebook' : '&#xe048;',
			'tg-facebook-2' : '&#xe049;',
			'tg-facebook-3' : '&#xe04a;',
			'tg-twitter' : '&#xe04b;',
			'tg-twitter-2' : '&#xe04c;',
			'tg-twitter-3' : '&#xe04d;',
			'tg-pinterest' : '&#xe04e;',
			'tg-pinterest-2' : '&#xe04f;',
			'tg-tumblr' : '&#xe050;',
			'tg-tumblr-2' : '&#xe051;',
			'tg-android' : '&#xe052;',
			'tg-soundcloud' : '&#xe053;',
			'tg-apple' : '&#xe054;',
			'tg-wrench' : '&#xe055;',
			'tg-phone-hang-up' : '&#xe056;',
			'tg-phone' : '&#xe057;',
			'tg-cart' : '&#xe058;',
			'tg-cart-2' : '&#xe059;',
			'tg-cart-3' : '&#xe05a;',
			'tg-calendar' : '&#xe05b;',
			'tg-calendar-2' : '&#xe05c;',
			'tg-print' : '&#xe05d;',
			'tg-clock-2' : '&#xe05e;',
			'tg-alarm' : '&#xe05f;',
			'tg-tag' : '&#xe060;',
			'tg-home-2' : '&#xe061;',
			'tg-expand' : '&#xe062;',
			'tg-cloud-download' : '&#xe063;',
			'tg-play-2' : '&#xe064;',
			'tg-camera-2' : '&#xe065;',
			'tg-film' : '&#xe066;',
			'tg-music' : '&#xe067;',
			'tg-headphones' : '&#xe068;',
			'tg-images' : '&#xe069;',
			'tg-location' : '&#xe06a;',
			'tg-envelop' : '&#xe06b;',
			'tg-location-2' : '&#xe06c;',
			'tg-pushpin' : '&#xe06d;',
			'tg-upload-2' : '&#xe06e;',
			'tg-box-remove' : '&#xe06f;',
			'tg-box-add' : '&#xe070;',
			'tg-download' : '&#xe071;',
			'tg-drawer' : '&#xe072;',
			'tg-drawer-2' : '&#xe073;',
			'tg-drawer-3' : '&#xe074;',
			'tg-bullhorn' : '&#xe075;',
			'tg-connection' : '&#xe076;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/tg-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};